{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.xAv3nGer",
    "module": "astra-platform",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 26,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "astra-platform-1.0.0.jar",
          "url": "astra-platform-1.0.0.jar",
          "size": 20037,
          "sha512": "6c2db3dd3fa4cef1e522945040eaeeda0063ab7491e7ab93947aed644e23ecc3a50ae3c7609b44c90a9598d97e84f5f480e4e913bf1a4698710690b540c84671",
          "sha256": "85b4eaa4a6d2c7c83cfe828ecb2ebd1877e3c6b292db922b8a01f9f03cade14b",
          "sha1": "02242cadd28deb1e930edda8b60fe2308cae7a50",
          "md5": "a7edbd7e1b15e22578cd1c0489ac26e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 26,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "5.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "astra-platform-1.0.0.jar",
          "url": "astra-platform-1.0.0.jar",
          "size": 20037,
          "sha512": "6c2db3dd3fa4cef1e522945040eaeeda0063ab7491e7ab93947aed644e23ecc3a50ae3c7609b44c90a9598d97e84f5f480e4e913bf1a4698710690b540c84671",
          "sha256": "85b4eaa4a6d2c7c83cfe828ecb2ebd1877e3c6b292db922b8a01f9f03cade14b",
          "sha1": "02242cadd28deb1e930edda8b60fe2308cae7a50",
          "md5": "a7edbd7e1b15e22578cd1c0489ac26e9"
        }
      ]
    }
  ]
}
